spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_spring_java_erudio?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
springdoc:
    pathsToMatch: /api/**/v1/**
    swagger-ui:
      use-root-path: true